spring.datasource.url=mysql://root:KtHLlSZXxYIGJICBXcgdNqdsTvPqmOXI@shinkansen.proxy.rlwy.net:53272/railway
spring.datasource.username=root
spring.datasource.password=AfKLViNmcVaPnZwngOcZWKvsmvJsVhHa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8081}
